# Generated by Django 4.1.5 on 2023-01-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.BooleanField(default=True),
        ),
    ]
