# Generated by Django 4.1.5 on 2023-01-29 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_orders_product_id_orders_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
