# Generated by Django 4.1.5 on 2023-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_alter_tickets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
